services:
  icecube-dev:
    build: .
    container_name: icecube-dev
    env_file:
      - .env
    ports:
      - "3331:3331"
    profiles:
      - dev
    command: ["./icecube", "-config", "config/icecube.dev.json"]

  icecube-prod:
    build: .
    container_name: icecube-prod
    env_file:
      - .env
    ports:
      - "3331:3331"
    profiles:
      - prod
    command: ["./icecube", "-config", "config/icecube.json"]
    volumes:
      - blob_data:/app/data/blobs
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - prod

volumes:
  postgres_data:
  blob_data:
